version: '3'

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: library/postgres:11.1-alpine
    ports:
      - 8080:8080